<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'UthandoContact\Module'                           => __DIR__ . '/Module.php',
    'UthandoContact\Form\Contact'                     => __DIR__ . '/src/UthandoContact/Form/Contact.php',
    'UthandoContact\Form\ContactSettings'             => __DIR__ . '/src/UthandoContact/Form/ContactSettings.php',
    'UthandoContact\InputFilter\Contact'              => __DIR__ . '/src/UthandoContact/InputFilter/Contact.php',
    'UthandoContact\Model\AbstractLine'               => __DIR__ . '/src/UthandoContact/Model/AbstractLine.php',
    'UthandoContact\Model\AddressLinesCollection'     => __DIR__ . '/src/UthandoContact/Model/AddressLinesCollection.php',
    'UthandoContact\Model\BusinessHoursCollection'    => __DIR__ . '/src/UthandoContact/Model/BusinessHoursCollection.php',
    'UthandoContact\Model\TransportListCollection'    => __DIR__ . '/src/UthandoContact/Model/TransportListCollection.php',
    'UthandoContact\Mvc\Controller\ContactController' => __DIR__ . '/src/UthandoContact/Mvc/Controller/ContactController.php',
    'UthandoContact\Mvc\Controller\Settings'          => __DIR__ . '/src/UthandoContact/Mvc/Controller/Settings.php',
    'UthandoContact\Options\CompanyOptions'           => __DIR__ . '/src/UthandoContact/Options/CompanyOptions.php',
    'UthandoContact\Options\DetailsOptions'           => __DIR__ . '/src/UthandoContact/Options/DetailsOptions.php',
    'UthandoContact\Options\FormOptions'              => __DIR__ . '/src/UthandoContact/Options/FormOptions.php',
    'UthandoContact\Options\GoogleMapOptions'         => __DIR__ . '/src/UthandoContact/Options/GoogleMapOptions.php',
    'UthandoContact\Service\Contact'                  => __DIR__ . '/src/UthandoContact/Service/Contact.php',
    'UthandoContact\View\Contact'                     => __DIR__ . '/src/UthandoContact/View/Contact.php',
);
