<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'uthando-contact/contact/index'     => __DIR__ . '/view/uthando-contact/contact/index.phtml',
    'uthando-contact/contact/thank-you' => __DIR__ . '/view/uthando-contact/contact/thank-you.phtml',
    'uthando-contact/settings/index'    => __DIR__ . '/view/uthando-contact/settings/index.phtml',
);
