<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'uthando-contact/contact/index'                      => __DIR__ . '/view/uthando-contact/contact/index.phtml',
    'uthando-contact/contact/thank-you'                  => __DIR__ . '/view/uthando-contact/contact/thank-you.phtml',
    'uthando-contact/email-template/default-content'     => __DIR__ . '/view/uthando-contact/email-template/default-content.phtml',
    'uthando-contact/email-template/default-layout'      => __DIR__ . '/view/uthando-contact/email-template/default-layout.phtml',
    'uthando-contact/email-template/default-sender-copy' => __DIR__ . '/view/uthando-contact/email-template/default-sender-copy.phtml',
    'uthando-contact/settings/index'                     => __DIR__ . '/view/uthando-contact/settings/index.phtml',
);
